/* Errro Codes */
export const ErrorCodes = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  PASSWORD_INCORRECT: "PASSWORD_INCORRECT",

  GOOGLE_NOT_LINKED: "GOOGLE_NOT_LINKED",

  EMAIL_DELIVERY_FAILED: "EMAIL_DELIVERY_FAILED",

  SELFGUIDED_ALREADY_PURCHASED: "SELFGUIDED_ALREADY_PURCHASED",
  COACHING_ALREADY_PURCHASED: "COACHING_ALREADY_PURCHASED",
  STRIPE_COUPON_INVALID: "STRIPE_COUPON_INVALID",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  UNAUTHORIZED: "UNAUTHORIZED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",

  RESET_OTP_EXPIRED: "RESET_OTP_EXPIRED",
  RESET_OTP_INVALID: "RESET_OTP_INVALID",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
};

/* App custom error */
class AppError extends Error {
  constructor(code, message, status, isOperational, details = null) {
    super(message);
    ((this.code = code),
      (this.message = message),
      (this.status = Number(status)),
      (this.isOperational = isOperational),
      (this.details = details),
      (this.name = this.constructor.name));

    Error.captureStackTrace(this, this.contructor);
  }
}

export default AppError;
