
# all request should includes credencails
# https://true-love-backend-nodejs.onrender.com/

GET https://true-love-backend-nodejs.onrender.com/

###
# sign up a new user
POST https://true-love-backend-nodejs.onrender.com/api/auth/signup
Content-Type: application/json

{
  "fullName" : "Bulus Hamnu",
  "phone" : "+2349068556962",
  "age" : 21,
  "password" : "Hamnubulus@888",
  "email" : "hamnubulus@gmail.com"
}

# response example: 200
# {
#   "status": true,
#   "message": "User created sucessfully.",
#   "data": {
#     "userId": "68aa43566bb6df0d2c51d6a8",
#     "fullName": "Bulus Hamnu",
#     "email": "hamnubulus@gmail.com",
#     "phone": "+2349068556962",
#     "age": 21,
#     "transactions": [],
#     "hasPremium": false,
#     "programProgress": {
#       "week": 0,
#       "totalWeek": 6
#     },
#     "_id": "68aa43566bb6df0d2c51d6aa",
#     "createdAt": "2025-08-23T22:40:22.354Z",
#     "__v": 0
#   }
# }
# 400 missing feilds
# {
#   "status": false,
#   "message": "Please provide all required feilds: fullName, phone, age, password and email."
# }
# 400 examples
# {
#   "status": true,
#   "message": "User already exist."
# }

###

# verify user email address from the code that was send in the email when signing up
POST https://true-love-backend-nodejs.onrender.com/api/auth/verify-email
Content-Type: application/json

{
  "code" : "565816"
}

#  response example: 200
# {
#   "status": true,
#   "message": "Email verify sucessful",
#   "data": {
#     "programProgress": {
#       "week": 0,
#       "totalWeek": 6
#     },
#     "_id": "68aa43566bb6df0d2c51d6aa",
#     "userId": "68aa43566bb6df0d2c51d6a8",
#     "fullName": "Bulus Hamnu",
#     "email": "hamnubulus@gmail.com",
#     "phone": "+2349068556962",
#     "age": 21,
#     "transactions": [],
#     "hasPremium": false,
#     "createdAt": "2025-08-23T22:40:22.354Z",
#     "__v": 0,
#     "isVerified": true
#   }
# }
# 400 missing feild :code
# {
#   "status": false,
#   "message": "Please provide verification code."
# }
# 400 example
# {
#   "status": true,
#   "message": "Code expired or code is invalid"
# }

###

# resend email verification code
POST https://true-love-backend-nodejs.onrender.com/api/auth/resend-email
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiODAxY2QzYTJmNDczODMyNWNkYTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYwNzAwODMsImV4cCI6MTc1ODY2MjA4M30.FomW-yq50dDTHocu3vVS8erZ45mBo9i_JlOh2zjuGac


# response emample: 200
# {
#   "status" : true,
#   "message" : "Email was sent sucessfully."
# }
# 400 example
# {
#   "status": false,
#   "message": "User is already verified"
# }



###

# get user profile
GET https://true-love-backend-nodejs.onrender.com/api/me
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOGFiNzlmMWE5NTY3NWNjZjc5YzMiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYwNzI3NDYsImV4cCI6MTc1ODY2NDc0Nn0.9UqO0owEPHyilAoFCuv-TVqg2Y03YkZa-mDRMCtSZvQ

# response example 200
# {
#   "status": true,
#   "message": "Profile retrieved sucessfully",
#   "data": {
#     "programProgress": {
#       "week": 0,
#       "totalWeek": 6
#     },
#     "_id": "68aa43566bb6df0d2c51d6aa",
#     "userId": "68aa43566bb6df0d2c51d6a8",
#     "fullName": "Bulus Hamnu",
#     "email": "hamnubulus@gmail.com",
#     "phone": "+2349068556962",
#     "age": 21,
#     "transactions": [],
#     "hasPremium": false,
#     "createdAt": "2025-08-23T22:40:22.354Z",
#     "__v": 0,
#     "isVerified": true
#   }
# }
# 500 example
# {
#   "status" : false,
#   "message" : "An error occur retriving user profile"
# }

###

# update user profile
PATCH  https://true-love-backend-nodejs.onrender.com/api/me
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOGFiNzlmMWE5NTY3NWNjZjc5YzMiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYwNzI3NDYsImV4cCI6MTc1ODY2NDc0Nn0.9UqO0owEPHyilAoFCuv-TVqg2Y03YkZa-mDRMCtSZvQ
Content-Type: application/json

{
  "userId" : "bfegf79gre8hed0iewihg",
  "fullName" : "Bulus Madu",
  "age" : 21,
  "programProgress" : {}
}

# respone example 200 sucesss
# only allowedFields = ["fullName", "phone",, "age", "programProgress" ] for now allowed fields so for the above example "programProgress" : {} will not update
# 
# {
#   "status": true,
#   "message": "Profile updated sucessfully.",
#   "data": {
#     "programProgress": {
#       "week": 0,
#       "totalWeek": 6
#     },
#     "_id": "68aaf4d7b7eddcb6c2fdd774",
#     "userId": "68aaf4d7b7eddcb6c2fdd772",
#     "fullName": "Bulus Hamnu",
#     "email": "hamnubulus@gmail.com",
#     "phone": "+2349068556962",
#     "age": 22,
#     "transactions": [],
#     "hasPremium": false,
#     "createdAt": "2025-08-24T11:17:43.853Z",
#     "__v": 0
#   }
# }
# 400 bad resquest when you send empty body
# {
#   "status": false,
#   "message": "Please provide data to update"
# }


###

// user forget password and request for reset
POST https://true-love-backend-nodejs.onrender.com/api/auth/forget-password
Content-Type: application/json

{
  "email" : "hamnubulus@gmail.com"
}

# response example 200
# {
#   "status": true,
#   "message": "Password reset email was sent sucessfully."
# }
# 500 example 
# {
#   "status" : false,
#   "message" : "An error occur while sending code"
# }
# 400 missing feild : email
# {
#   "status": false,
#   "message": "Please provide an email."
# }


###

# code is verify and now front can send new password
POST https://true-love-backend-nodejs.onrender.com/api/auth/verify-password-reset-code
Content-Type: application/json

{
  "code" : "185239"
}

# 200 response example 
# {
#   "status": false,
#   "message": "Code is valid"
# }
# 400 example
# {
#   "status": false,
#   "message": "Code expired or code is invalid"
# }
# 400 missing feild : code
# {
#   "status": false,
#   "message": "Please provide verification code."
# }



###

# send new password
POST https://true-love-backend-nodejs.onrender.com/api/auth/reset-password
Content-Type: application/json

{
  "email" : "hamnubulus@gmail.com",
  "password" : "Bulus@8923_"
}

# 200 response example 
# {
#   "status": true,
#   "message": "Password was reset sucessfully."
# }
# 404response example 
# {
#   "status": false,
#   "message": "User does no exist."
# }
# 400 missing feild 
# {
#   "status": false,
#   "message": "Missing email or password field."
# }
# 404 missing feild 
# {
#   "status": false,
#   "message": "Code not found."
# }


###

# log user in
POST https://true-love-backend-nodejs.onrender.com/api/auth/login
Content-Type: application/json

{
  "email" : "hamnubulus@gmail.com",
  "password" : "Hamnu@8923_"
}


# response example: 200
# {
#   "status": true,
#   "message": "Login sucessful, token is set in the cookie header."
# }
# response 400
# {
#   "status": false,
#   "message": "Missing email or password field."
# }
# 404 
# {
#   "status": false,
#   "message": "User does not exist."
# }
# 401
# {
#   "status": false,
#   "message": "Incorect password."
# }


###

# log a user out
POST https://true-love-backend-nodejs.onrender.com/api/auth/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOGFiNzlmMWE5NTY3NWNjZjc5YzMiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYwNzI3NDYsImV4cCI6MTc1ODY2NDc0Nn0.9UqO0owEPHyilAoFCuv-TVqg2Y03YkZa-mDRMCtSZvQ


# response example 200
# {
#   "status": true,
#   "message": "User logout sucessfully"
# }
# 400 bad request send nothing if the user is not log in


### create stripe checkout

GET https://true-love-backend-nodejs.onrender.com/api/payment/create-checkout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM

# response example 200
# {
#   "status": true,
#   "data": {
#     "url": "stripe checkout url"
#   }
# }
# res example 409 
# {
#   "status": true,
#   "message": "User already paid for the coaching-program."
# }
# res example 500 
# {
#   "status": false,
#   "message": "An error occur."
# }

####

GET http://localhost:3000/api/payment/checkout-self-guided
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM

# response type 200
# {
#   "status": true,
#   "data": {
#     "url": "stripe checkout url"
#   }
# }
# 
# 409 error 
# {
#   "status": true,
#   "message": "User already paid for the self-guided program."
# }
# res example 500 
# {
#   "status": false,
#   "message": "An error occur."
# }


####

GET http://localhost:3000/api/me/self-guided-progress
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM

# response type 200
# {
#   "status": true,
#   "message": "Self-guided program progress retrieved sucessfully",
#   "data": {
#     "week": 0,
#     "totalWeek": 6
#   }
# }
# 500 example 
# {
#   "status" : false,
#   "message" : "An unexpected error occured."
#   "error" : error
# }


###

PATCH https://true-love-backend-nodejs.onrender.com/api/me/self-guided-progress
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM
Content-Type: application/json

{
   "weekNumber" : 1
}

# response type 200
# {
#   "status": true,
#   "message": "Self-guided progress update sucessfully.",
#   "data": {
#     "week": 2,
#     "totalWeek": 6
#   }
# }
# 404 res example 
# {
#   "status": false,
#   "message": "Please provide the lastest week numnber."
# }
# 400 example 
# {
#   "status": false,
#   "message": "Week number cannot be less than 0 or greater than 6"
# }
# 
# 500 example 
# {
#   "status": false,
#   "message": "An unexpected error occured."
# }



###

# Stripe webhook
POST https://true-love-backend-nodejs.onrender.com/api/payment/stripe-webhook


###

# get all transaction
GET https://true-love-backend-nodejs.onrender.com/api/transactions
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM

# response type 200
# {
#   "status": true,
#   "message": "User transactions retrieved sucessfully",
#   "data": [
#     {
#       "_id": "68ae10fde704fe2eaf6dd727",
#       "userId": "68ab9404d58b202aa5c234a1",
#       "amount": 150000,
#       "status": "pending",
#       "type": "coaching-program",
#       "paymentIntent": "pi_3S0SwuBgCenrcBqi0Gy3fIQ3",
#       "createdAt": "2025-08-26T19:54:37.979Z",
#       "__v": 0
#     },
#     {
#       "_id": "68ae129427c8b908f321a1aa",
#       "userId": "68ab9404d58b202aa5c234a1",
#       "amount": 4900,
#       "status": "pending",
#       "type": "self-guided-program",
#       "paymentIntent": "pi_3S0T3UBgCenrcBqi0VGbrsC3",
#       "createdAt": "2025-08-26T20:01:24.623Z",
#       "__v": 0
#     },
#     {
#       "_id": "68ae13be27c8b908f321a1af",
#       "userId": "68ab9404d58b202aa5c234a1",
#       "amount": 4900,
#       "status": "pending",
#       "type": "self-guided-program",
#       "paymentIntent": "pi_3S0T8HBgCenrcBqi0j2nZ4AL",
#       "createdAt": "2025-08-26T20:06:22.428Z",
#       "__v": 0
#     }
#   ]
# }
# 500 example 
# {
#   "status" : false,
#   "message" : "An unexpected error occured.",
#   "error" : error
# }


### 
# get all transaction

GET https://true-love-backend-nodejs.onrender.com/api/transactions/68ae10fde704fe2eaf6dd727
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbW51YnVsdXNAZ21haWwuY29tIiwiaWQiOiI2OGFiOTQwNGQ1OGIyMDJhYTVjMjM0YTEiLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzExMDQsImV4cCI6MTc1ODcyMzEwNH0.1yCL7zzuFsEd7eqc1rkLgpMwLihkDO87GVVdPUyzkWM

# response type 200
# {
#   "status": true,
#   "message": "Transaction retrieved sucessfully",
#   "data": {
#     "_id": "68ae10fde704fe2eaf6dd727",
#     "userId": "68ab9404d58b202aa5c234a1",
#     "amount": 150000,
#     "status": "pending",
#     "type": "coaching-program",
#     "paymentIntent": "pi_3S0SwuBgCenrcBqi0Gy3fIQ3",
#     "createdAt": "2025-08-26T19:54:37.979Z",
#     "__v": 0
#   }
# }
# 404 example 
# {
#   "status" : false,
#   "message" : "An unexpected error occured.",
#   "error" : error
# }
